site_url : https://asalvadorc.github.io/BBDD_NoSQL
site_name: BBDD - Bases de Dades

extra_css:
  - css/extra.css
  - img/favicon.ico 

theme: 
  name: readthedocs
  highlightjs: true
  logo: assets/logocaminas.png
  features:
    - content.code.copy  # Habilita el botón de copiar en bloques de código

markdown_extensions:
  - admonition
  - pymdownx.emoji
 # - pymdownx.extra
 # - pymdownx.superfences 
 # - pymdownx.highlight # Resalta sintaxis
  - pymdownx.superfences # Permite bloques de código avanzados
  - tables    
  - attr_list
  

nav:

- BD NoSQL:
  - 1 - Introducció: 1__introducci.md
- REDIS:  
  - 2 - Bases de Dades Clau-Valor (Redis): 2__bases_de_dades_clauvalor.md
  ## - Exercicis: exercicis_redis.md
- MONGO:  
  - 3 - MongoDB : 3__mongodb.md
  ## - Exercicis: exercicis_mongo.md
  - 4 - Relacions en MongoDB: 4_relaciones_mongo.md
  - Práctica Mongo: 5_actividad_mongo.md
